[package]
name = "rust-hl7"
version = "0.1.0"
authors = ["wokket <wokket@gmail.com>"]
edition = "2018"
description = "HL7 Parser and object builder? query'er? - experimental only at any rate"
license = "MIT OR Apache-2.0"

[lib]
name="rusthl7"
path="src/lib.rs"

[dependencies]
chrono = "0.4"
failure = "0.1"